---
version: "3"

services:
  bursar:
    image: ghcr.io/avirut/bursar:master
    container_name: bursar
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./config:/etc/bursar/config